core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home' ),
    path('about/', views.About.as_view(), name='about' ),
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logado/', views.Logado.as_view(), name='logado'),
    
]

sigconstruct/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('stock/', include('stock.urls', namespace='stock')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="container d-flex justify-content-between">
        <div class="align-items-center">
            <a class="logo d-flex align-items-center">
                <img src="{% static 'assets/img/logo.png' %}" alt="logo sistema">
                <span class="d-none d-lg-block">SigConstruct</span>
            </a>    
        </div>
    </div>

</header>
{% endblock  %}

{% block content %}
<div class="container">
    <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 col-md-6 d-flex flex-column align-items-center justify-content-center">
            <div class=" mb-3">
              <div class="card-body text-center">

                <div class="pt-4 pb-2">
                  <h3 class="card-title mb-3 text-center pb-0 fs-4">Sobre</h3>
                  <p>O sistema <b>CONSTRUCT</b> é uma aplicação web que permite o gerenciamento eficiente das 

                    atividades relacionadas à loja de materiais de construção.Os principais módulos incluem cadastro, 
                    
                    listagem, busca e exclusão de gerentes, vendedores, fornecedores, produtos, clientes, controle de estoque,
                    
                    registro de vendas, emissão de nota fiscal e geração de relatórios.
                    </p>
                    <a href="{% url 'pages:home' %}" class="btn btn-primary">
                        <i class="bi bi-box-arrow-in-left"></i><span> Home</span>
                    </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
</div>

{% endblock  %}

templates/pages/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-8 col-md-6 d-flex flex-column align-items-center justify-content-center">
              <div class=" mb-3">
                <div class="card-body text-center">

                  <div class="pt-4 pb-2">
                    <h3 class="card-title mb-3 text-center pb-0 fs-4">Bem vindo(a) ao <b>SigConstruct!</b></h3>
                    <p>O sistema de gerenciamento para sua loja de materiais de construção.</p>
                    <a href="{% url 'accounts:login' %}" class="btn btn-primary">
                        <i class="bi bi-box-arrow-in-right"></i><span> Login</span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
{% endblock  %}