apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logado/', views.Logado.as_view(), name='logado'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('upload/image/', views.UploadImageView.as_view(), name='upload_image'),
    path('remove/image/', views.RemoveImageView.as_view(), name='remove_image'),
    
    path('criar/fornecedor', views.CriarFornecedor.as_view(), name='criar_fornecedor'),
    path('listar/fornecedor', views.ListarFornecedor.as_view(), name='listar_fornecedor'),
    path('editar/<str:fornecedor_id>/fornecedores', views.EditarFornecedor.as_view(), name='editar_fornecedor'),
    path('excluir/<str:fornecedor_id>/fornecedor', views.ExcluirFornecedor.as_view(), name='excluir_fornecedor'),
    
    path('criar/cliente', views.CriarCliente.as_view(), name='criar_cliente'),
    path('listar/clientes', views.ListarClientes.as_view(), name='listar_clientes'),
    path('editar/<str:cliente_id>/cliente', views.EditarCliente.as_view(), name='editar_cliente'),
    path('excluir/<str:cliente_id>/cliente', views.ExcluirCliente.as_view(), name='excluir_cliente'),
]

apps/stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'

urlpatterns = [
    path('criar/categoria', views.CriarCategoria.as_view(), name='criar_categoria'),
    path('listar/categorias', views.ListarCategorias.as_view(), name='listar_categorias'),
    path('editar/<str:categoria_id>/categoria', views.EditarCategoria.as_view(), name='editar_categoria'),
    path('excluir/<str:categoria_id>/categoria', views.ExcluirCategoria.as_view(), name='excluir_categoria'),
    
    path('criar/produto', views.CriarProduto.as_view(), name='criar_produto'),
    path('listar/produtos', views.ListarProdutos.as_view(), name='listar_produtos'),
    path('editar/<str:produto_id>/produto', views.EditarProduto.as_view(), name='editar_produto'),
    path('excluir/<str:produto_id>/produto', views.ExcluirProduto.as_view(), name='excluir_produto'),
    
    path('adicionar/estoque/<str:produto_id>', views.AdicionarEstoque.as_view(), name='adicionar_estoque'),
    path('listar/estoque', views.ListarEstoque.as_view(), name='listar_estoque'),
    
    path('realizar/venda', views.RealizarVenda.as_view(), name='realizar_venda'),
    path('listar/venda', views.ListarVendas.as_view(), name='listar_vendas'),
    path('excluir/<str:venda_id>/venda', views.ExcluirVenda.as_view(), name='excluir_venda'),
    path('venda/<int:venda_id>/', views.DetalharVenda.as_view(), name='detalhar_venda'),
    
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home' ),
    path('about/', views.About.as_view(), name='about' ),
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logado/', views.Logado.as_view(), name='logado'),
    
]

sigconstruct/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('stock/', include('stock.urls', namespace='stock')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class Usuario(AbstractUser):
    nome = models.CharField(max_length=200, null=False)
    cpf = models.CharField(max_length=15, null=True)
    telefone = models.CharField(max_length=20, null=True)
    imagem = models.ImageField(upload_to='usuarios/', null=True)
    
    email = models.EmailField(unique=True)
    
    def primeiro_nome(self):
        split_nome = self.nome.split(' ')
        return split_nome[0]

class Fornecedor(models.Model):
    nome = models.CharField(max_length=200, null=False)
    telefone = models.CharField(max_length=20, null=True)
    cnpj = models.CharField(max_length=15, null=True)
    
    email = models.EmailField(unique=True)
    
    def primeiro_nome(self):
        split_nome = self.nome.split(' ')
        return split_nome[0]
    
    
class Endereco(models.Model):
    logradouro = models.CharField(max_length=200, null=True)
    numero = models.CharField(max_length=10, null=True)
    cep = models.CharField(max_length=10, null=True)
    cidade = models.CharField(max_length=100, null=True)
    estado = models.CharField(max_length=100, null=True)


class Cliente(models.Model):
    nome = models.CharField(max_length=200, null=False)
    telefone = models.CharField(max_length=20, null=True)
    cpf = models.CharField(max_length=15, null=True)
    email = models.EmailField(unique=True)
    endereco = models.OneToOneField(Endereco, on_delete=models.SET_NULL, null=True)

    def primeiro_nome(self):
        split_nome = self.nome.split(' ')
        return split_nome[0]

apps/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.exceptions import ValidationError
from django.views import View
import requests
from django.http import JsonResponse

from .models import Usuario
from .models import Fornecedor
from .models import Endereco
from .models import Cliente


class Login(View):
    def get(self, request):
        return render(request, 'accounts/registration/login.html')

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('accounts:logado')
        else:
            messages.error(request, 'Credenciais inválidas. Tente novamente.')
            return redirect('accounts:login')

class SignUp(View):
    def get(self, request):
        return render(request, 'accounts/registration/signup.html')

    def post(self, request):
        nome = request.POST['nome']
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        cpf = request.POST['cpf']
        telefone = request.POST['telefone']
        imagem = request.FILES.get('imagem')  

        if Usuario.objects.filter(email=email).exists():
            messages.error(request, 'Email já está cadastrado.')
            return redirect('accounts:signup')

        try:
            usuario = Usuario.objects.create_user(username=username, email=email, password=password)
            usuario.nome = nome
            usuario.cpf = cpf
            usuario.telefone = telefone
            usuario.imagem = imagem
            usuario.save()
            messages.success(request, 'Conta criada com sucesso!')
            return redirect('accounts:login')
        except ValidationError as e:
            messages.error(request, f'Erro ao criar conta: {str(e)}')
            return redirect('accounts:signup')


@method_decorator(login_required, name='dispatch')
class Logado(View):
    def get(self, request):
        return render(request, 'accounts/logado.html')
  
    
@method_decorator(login_required, name='dispatch')
class Logout(View):
    def get(self, request):
        logout(request)
        return redirect('pages:home')
    
@method_decorator(login_required, name='dispatch')
class Profile(View):
    template_name = 'accounts/profile.html'

    def get(self, request):
        return render(request, self.template_name, {'user': request.user})

    def post(self, request):
        usuario = request.user
        usuario.nome = request.POST.get('nome', usuario.nome)
        usuario.cpf = request.POST.get('cpf', usuario.cpf)
        usuario.telefone = request.POST.get('telefone', usuario.telefone)
        usuario.email = request.POST.get('email', usuario.email)

        # Verifique se o campo 'nova_imagem' existe antes de atribuir a imagem do perfil
        if 'nova_imagem' in request.FILES:
            usuario.imagem = request.FILES['nova_imagem']

        # Verifique se os campos para alterar a senha foram preenchidos
        current_password = request.POST.get('currentPassword')
        new_password = request.POST.get('newPassword')
        renew_password = request.POST.get('renewPassword')

        if current_password and new_password and renew_password:
            # Verifique se a senha atual está correta
            if usuario.check_password(current_password):
                # Verifique se a nova senha e a repetição da senha correspondem
                if new_password == renew_password:
                    # Defina a nova senha usando a função set_password
                    usuario.set_password(new_password)
                    messages.success(request, 'Senha alterada com sucesso!')
                else:
                    messages.error(request, 'A nova senha e a repetição da senha não correspondem. Tente novamente.')
            else:
                messages.error(request, 'A senha atual está incorreta. Tente novamente.')

        try:
            usuario.save()
            messages.success(request, 'Perfil atualizado com sucesso!')
        except Exception as e:
            messages.error(request, f'Erro ao atualizar perfil: {str(e)}')

        return redirect('accounts:profile')


@method_decorator(login_required, name='dispatch')
class UploadImageView(View):
    def post(self, request):
        nova_imagem = request.FILES.get('nova_imagem')
        if nova_imagem:
            request.user.imagem = nova_imagem
            request.user.save()
            messages.success(request, 'Imagem de perfil atualizada com sucesso!')
        return redirect('accounts:profile')
    
@method_decorator(login_required, name='dispatch')
class RemoveImageView(View):
    def get(self, request):
        if request.user.imagem:
            request.user.imagem.delete()
            request.user.save()
            messages.success(request, 'Imagem de perfil removida com sucesso!')
        return redirect('accounts:profile')
    

#================================================================
# VIEWS FORNECEDORES

@method_decorator(login_required, name='dispatch')
class CriarFornecedor(View):
    template_name = 'accounts/fornecedores/criar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        nome = request.POST['nome']
        cnpj = request.POST['cnpj']
        telefone = request.POST['telefone']
        email = request.POST['email']

        # Cria um novo objeto Fornecedor e salvá-lo no banco de dados
        Fornecedor.objects.create(nome=nome, cnpj=cnpj, telefone=telefone, email=email)
        messages.success(request, 'Fornecedor cadastrado com sucesso!')
        
        # Redireciona o usuário para outra página, como a lista de fornecedores
        return redirect('accounts:criar_fornecedor') 

    
@method_decorator(login_required, name='dispatch')
class ListarFornecedor(View):
    template_name = 'accounts/fornecedores/listar.html'

    def get(self, request):
        fornecedores = Fornecedor.objects.all()
        return render(request, self.template_name, {'fornecedores': fornecedores})


@method_decorator(login_required, name='dispatch')
class EditarFornecedor(View):
    template_name = 'accounts/fornecedores/editar.html'

    def get(self, request, fornecedor_id):
        fornecedor = get_object_or_404(Fornecedor, id=fornecedor_id)
        return render(request, self.template_name, {'fornecedor': fornecedor})

    def post(self, request, fornecedor_id):
        fornecedor = get_object_or_404(Fornecedor, id=fornecedor_id)

        nome = request.POST['nome']
        cnpj = request.POST['cnpj']
        telefone = request.POST['telefone']
        email = request.POST['email']

        fornecedor.nome = nome
        fornecedor.cnpj = cnpj
        fornecedor.telefone = telefone
        fornecedor.email = email
        fornecedor.save()

        messages.success(request, 'Fornecedor atualizado com sucesso!')

        return redirect('accounts:listar_fornecedor')
    
@method_decorator(login_required, name='dispatch')
class ExcluirFornecedor(View):
    template_name = 'accounts/fornecedores/excluir.html'
    
    def get(self, request, fornecedor_id):
        fornecedor = get_object_or_404(Fornecedor, id=fornecedor_id)
        return render(request, self.template_name, {'fornecedor': fornecedor})
    
    def post(self, request, fornecedor_id):
        fornecedor = get_object_or_404(Fornecedor, id=fornecedor_id)
        fornecedor.delete()
        messages.success(request, 'Fornecedor excluído com sucesso!')
        
        return redirect('accounts:listar_fornecedor')  

#================================================================
# VIEWS CLIENTES

@method_decorator(login_required, name='dispatch')
class CriarCliente(View):
    template_name = 'accounts/clientes/criar.html' 

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        nome = request.POST.get('nome')
        telefone = request.POST.get('telefone')
        cpf = request.POST.get('cpf')
        email = request.POST.get('email')

        logradouro = request.POST.get('logradouro')
        numero = request.POST.get('numero')
        cep = request.POST.get('cep')
        cidade_estado_api_url = f'https://viacep.com.br/ws/{cep}/json/'
        cidade_estado_api_response = requests.get(cidade_estado_api_url)
        if cidade_estado_api_response.status_code == 200:
            cidade_estado_data = cidade_estado_api_response.json()
            cidade = cidade_estado_data.get('localidade')
            estado = cidade_estado_data.get('uf')
        else:
            cidade = None
            estado = None

        # Criar o objeto Endereco
        endereco = Endereco.objects.create(
            logradouro=logradouro,
            numero=numero,
            cep=cep,
            cidade=cidade,
            estado=estado
        )

        # Criar o objeto Cliente associado ao endereço criado acima
        Cliente.objects.create(
            nome=nome,
            telefone=telefone,
            cpf=cpf,
            email=email,
            endereco=endereco
        )

        return redirect('accounts:criar_cliente') 
    
class ListarClientes(View):
    template_name = 'accounts/clientes/listar.html'

    def get(self, request):
        clientes = Cliente.objects.all()
        return render(request, self.template_name, {'clientes': clientes})
    

class EditarCliente(View):
    template_name = 'accounts/clientes/editar.html'

    def get(self, request, cliente_id):
        cliente = get_object_or_404(Cliente, id=cliente_id)

templates/accounts/fornecedores/excluir.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
    <a class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo.png' %}" alt="">
        <span class="d-none d-lg-block">SigConstruct</span>
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-bell"></i>
                    <span class="badge bg-primary badge-number">4</span>
                </a>

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                    <li class="dropdown-header">
                        Você tem 4 novas notificações
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">Visualisar Todas</span></a>
                    </li>
                    <li><hr class="dropdown-divider"></li>
                    <li class="notification-item">
                        <i class="bi bi-exclamation-circle text-warning"></i>
                        <div>
                            <h4>Vendas</h4>
                            <p>Você realizou uma venda e ganhou 20% de comissão</p>
                            <p>30 min. jun</p>
                        </div>
                    </li>
                    <li><hr class="dropdown-divider"></li>
                    <li class="notification-item">
                        <i class="bi bi-x-circle text-danger"></i>
                        <div>
                            <h4>Estoque</h4>
                            <p>O produto tintas está chegando ao limite mínimo do estoque</p>
                            <p>1 hr. jun</p>
                        </div>
                    </li>
                    <li><hr class="dropdown-divider"></li>
                    <li class="dropdown-footer">
                        <a href="#">Exibir todas as notificações</a>
                    </li>
                </ul>

            </li><!-- End Notification Nav -->

        <li class="nav-item dropdown">

        <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-chat-left-text"></i>
            <span class="badge bg-success badge-number">3</span>
        </a><!-- End Messages Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
            <li class="dropdown-header">
                Você tem 3 novas mensagens
                <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">Visualizar Todas</span></a>
            </li>
            <li><hr class="dropdown-divider"></li>

            <li class="message-item">
                <a href="#">
                    <img src="{% static 'assets/img/messages-1.jpg' %}" alt="" class="rounded-circle">
                    <div>
                    <h4>Maria Hudson</h4>
                    <p>Você poderia realizar a compra de mais Tintas, o estoque precisa ser renovado</p>
                    <p>4 hrs. jun</p>
                    </div>
                </a>
            </li>
            <li><hr class="dropdown-divider"></li>

            <li class="message-item">
                <a href="#">
                    <img src="{% static 'assets/img/messages-2.jpg' %}" alt="" class="rounded-circle">
                    <div>
                    <h4>Anna Nelson</h4>
                    <p>A Reunião de Gerência foi cancelada</p>
                    <p>6 hrs. jun</p>
                    </div>
                </a>
            </li>
            <li> <hr class="dropdown-divider"></li>
            <li class="dropdown-footer">
                <a href="#">Exibir totas as mensagens</a>
            </li>

        </ul>

        </li><!-- End Messages Nav -->

        <li class="nav-item dropdown pe-3">

            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                {% if user.imagem %}
                <img src="{{ user.imagem.url }}" alt="Imagem do usuário" class="rounded-circle">
                {% else %}
                <img src="/media/avatars/default-avatar.jpg" alt="Avatar padrão">
                {% endif %}

            </a><!-- End Profile Iamge Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
                <h6>{{user.nome}}</h6>
            </li>
            <li><hr class="dropdown-divider"></li>

            <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'accounts:profile' %}">
                    <i class="bi bi-person"></i>
                    <span>Meu Perfil</span>
                </a>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'accounts:logout' %}">
                    <i class="bi bi-box-arrow-right"></i>
                    <span>Sair</span>
                </a>
            </li>
        </ul>
        </li>
    </ul>
</nav>
</header>

<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'accounts:logado' %}">
              <i class="bi bi-grid"></i>
              <span>Dashboard</span>
            </a>
          </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link" data-bs-target="#fornecedores-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-menu-button-wide"></i><span>Fornecedores</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="fornecedores-nav" class="nav-content collapse show" data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'accounts:criar_fornecedor' %}">
                        <i class="bi bi-circle"></i><span>Cadastrar</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:listar_fornecedor' %}">
                        <i class="bi bi-circle"></i><span>Listar</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Fornecedores Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#clientes-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-people"></i><span>Clientes</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="clientes-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'accounts:criar_cliente' %}">
                        <i class="bi bi-circle"></i><span>Cadastrar</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:listar_clientes' %}">
                        <i class="bi bi-circle"></i><span>Listar</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Clientes Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#produtos-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-boxes"></i><span>Produtos</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="produtos-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'stock:listar_categorias' %}">
                        <i class="bi bi-circle"></i><span>Categorias</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'stock:criar_produto' %}">
                        <i class="bi bi-circle"></i><span>Cadastrar</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'stock:listar_produtos' %}">
                        <i class="bi bi-circle"></i><span>Listar</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Produtos Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#estoque-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-box2"></i><span>Estoque</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="estoque-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'stock:listar_estoque' %}">
                        <i class="bi bi-circle"></i><span>Listar</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Estoque Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#vendas-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-cart3"></i><span>Vendas</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="vendas-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'stock:realizar_venda' %}">
                        <i class="bi bi-circle"></i><span>Realizar Venda</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'stock:listar_vendas' %}">
                        <i class="bi bi-circle"></i><span>Listar Vendas</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Vendas Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#relatorios-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-clipboard2-data"></i><span>Relatórios</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="relatorios-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="relatorios-bootstrap.html">
                        <i class="bi bi-circle"></i><span>Fornecedores</span>
                    </a>
                </li>
                <li>
                    <a href="relatorios-remix.html">
                        <i class="bi bi-circle"></i><span>Clientes</span>
                    </a>
                </li>
                <li>
                    <a href="relatorios-remix.html">
                        <i class="bi bi-circle"></i><span>Produtos</span>
                    </a>
                </li>
                <li>
                    <a href="relatorios-remix.html">
                        <i class="bi bi-circle"></i><span>Estoque</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="pages-contact.html">
              <i class="bi bi-envelope"></i>
              <span>Contatos</span>
            </a>
        </li><!-- End Contact Page Nav -->
    </ul>
</aside>
<main id="main" class="main">
    <div class="pagetitle filter" style="display: flex; justify-content: space-between;">
        <h1 style="margin: 0;">Excluir Fornecedor</h1>   
    </div>
    <section class="section dashboard">
        <div class="row">
            <div class="col-12">
                <div class="card recent-sales overflow-auto">
                    <div class="card-body">
                        <p class="mt-4">Você tem certeza que deseja excluir o Fornecedor "<b>{{ fornecedor.nome }}</b>"?</p>
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success btn-sm">Confirmar</button>
                            <a class="btn btn-secondary btn-sm" href="{% url 'accounts:listar_fornecedor' %}" style="margin-left: auto;">Voltar</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>SigConstruct</span></strong>.
    </div>
</footer><!-- End Footer -->
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
{% endblock  %}