core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home' ),
    path('about/', views.About.as_view(), name='about' ),
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logado/', views.Logado.as_view(), name='logado'),
    
]

sigconstruct/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('stock/', include('stock.urls', namespace='stock')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Endereco(models.Model):
    ESTADO_CHOICES = [
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'),
    ]
    logradouro = models.CharField(max_length=100)
    numero = models.CharField(max_length=20)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=2, choices=ESTADO_CHOICES)
    
    def __str__(self):
        return f"{self.estado}"


class Usuario(AbstractUser):
    nome = models.CharField(max_length=200, null=False)
    cpf = models.CharField(max_length=15, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    imagem = models.ImageField(upload_to='usuarios/', null=True, blank=True)
    endereco = models.OneToOneField(
        Endereco,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )
    email = models.EmailField(unique=True)
    
    def primeiro_nome(self):
        split_nome = self.nome.split(' ')
        return split_nome[0]


class Material(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()

    def __str__(self):
        return self.nome
    
    
class Fornecedor(models.Model):
    nome = models.CharField(max_length=200)
    cnpj = models.CharField(max_length=18)
    telefone = models.CharField(max_length=20)
    email = models.EmailField()
        
    def primeiro_nome(self):
        split_nome = self.nome.split(' ')
        return split_nome[0] 


class Compra(models.Model):
    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    preco_custo = models.DecimalField(max_digits=10, decimal_places=2)
    data_compra = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.material.nome
      
    
class Produto(models.Model):
    nome = models.CharField(max_length=100)
    preco_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    imagem = models.ImageField(upload_to='produtos/', null=True, blank=True)
    estoque = models.PositiveIntegerField(default=0)
    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome




core/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import Usuario
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View

class HomePage(View):
    def get(self, request):
        return render(request, 'home.html')


class About(View):
    def get(self, request):
        return render(request, 'about.html')


class Login(View):
    def get(self, request):
        return render(request, 'registration/login.html')

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('core:logado')  # redirecione para a página logado após o login
        else:
            messages.error(request, 'Credenciais inválidas. Tente novamente.')
            return redirect('core:login')


class SignUp(View):
    def get(self, request):
        return render(request, 'registration/signup.html')

    def post(self, request):
        nome = request.POST['nome']
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        
        if Usuario.objects.filter(email=email).exists():
            messages.error(request, 'Email já está cadastrado.')
            return redirect('core:signup')
        
        try:
            usuario = Usuario.objects.create_user(username=username, email=email, password=password)
            usuario.nome = nome
            usuario.save()
            messages.success(request, 'Conta criada com sucesso!')
            return redirect('core:login')
        except Exception as e:
            messages.error(request, f'Erro ao criar conta: {str(e)}')
            return redirect('core:signup')
        

@method_decorator(login_required, name='dispatch')
class Logado(View):
    def get(self, request):
        return render(request, 'registration/logado.html')
    
    


        

core/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="container d-flex justify-content-between">
        <div class="align-items-center">
            <a href="{% url 'core:home' %}" class="logo d-flex align-items-center">
                <img src="{% static 'assets/img/logo.png' %}" alt="logo sistema">
                <span class="d-none d-lg-block">SigConstruct</span>
            </a>    
        </div>
    </div>

</header>
{% endblock  %}

{% block main %}
<div class="container">
    <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 col-md-6 d-flex flex-column align-items-center justify-content-center">
            <div class=" mb-3">
              <div class="card-body text-center">

                <div class="pt-4 pb-2">
                  <h3 class="card-title mb-3 text-center pb-0 fs-4">Sobre</h3>
                  <p>O sistema <b>CONSTRUCT</b> é uma aplicação web que permite o gerenciamento eficiente das 

                    atividades relacionadas à loja de materiais de construção.Os principais módulos incluem cadastro, 
                    
                    listagem, busca e exclusão de gerentes, vendedores, fornecedores, produtos, clientes, controle de estoque,
                    
                    registro de vendas, emissão de nota fiscal e geração de relatórios.
                    </p>
                    <a href="{% url 'core:home' %}" class="btn btn-primary">
                        <i class="bi bi-box-arrow-in-left"></i><span> Home</span>
                    </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
</div>

{% endblock  %}

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-BR">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}SigConstruct{% endblock  %}</title>

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

    {% block header %}
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="container d-flex justify-content-between">
            <div class="align-items-center">
                <a href="{% url 'core:home' %}" class="logo d-flex align-items-center">
                    <img src="{% static 'assets/img/logo.png' %}" alt="logo sistema">
                    <span class="d-none d-lg-block">SigConstruct</span>
                </a>    
            </div>
          
            <nav class="header-nav ms-auto">
                <ul class="d-flex align-items-center">           
                    <li class="nav-item pe-3">
                        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="{% url 'core:about' %}">
                            <span class="d-none d-lg-block">Sobre</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>

    </header>
    {% endblock  %}
    
    {% block main %}
    {% endblock  %}


  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

core/templates/home.html
{% extends 'base.html' %}

{% block main %}
    <div class="container">
      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-8 col-md-6 d-flex flex-column align-items-center justify-content-center">
              <div class=" mb-3">
                <div class="card-body text-center">

                  <div class="pt-4 pb-2">
                    <h3 class="card-title mb-3 text-center pb-0 fs-4">Bem vindo(a) ao <b>SigConstruct!</b></h3>
                    <p>O sistema de gerenciamento para sua loja de materiais de construção.</p>
                    <a href="{% url 'core:login' %}" class="btn btn-primary">
                        <i class="bi bi-box-arrow-in-right"></i><span> Login</span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
{% endblock  %}